---
- name: DNS firewall
  community.general.ufw:
    rule: allow
    port: 53
    src: "{{ INTERNAL_NETWORK }}/{{ MASK }}"
  when: inventory_hostname in groups['dns_servers']
  ignore_errors: yes

- name: Install resolvconf
  ansible.builtin.apt:
    pkg: resolvconf
    state: present

# temp
- name: Add DNS server
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: nameserver {{ hostvars['dns'].ansible_host }}
    insertbefore: BOF
    state: present
  
# permanent
- name: Add DNS server
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    regexp: '^iface eth0.*'
    line: '\g<0>\ndns-nameserver {{ hostvars["dns"].ansible_host }}\n'
    backrefs: yes
    state: present

# - name: Restart your networking interface
#   ansible.builtin.shell: |
#     ifdown --force {{ internal_interface }} 
#     ip addr flush dev {{ internal_interface }} 
#     ifup --force {{ internal_interface }}

- name: Add client to DNS server
  ansible.builtin.lineinfile:
    path: "/etc/bind/zones/db.{{ DOMAIN }}"
    line: "{{ item }}\t\tIN\tA\t{{ hostvars[item].ansible_host }}"
    state: present
  loop: "{{ ansible_play_hosts }}"
  when: inventory_hostname in groups['dns_servers']

- name: Reload dns server  
  ansible.builtin.systemd:
    name: named
    state: reloaded
  when: inventory_hostname in groups['dns_servers']
