---
- name: Download firewall
  ansible.builtin.apt:
    pkg: ufw
    state: present

- name: Deny policy
  community.general.ufw:
    policy: deny

- name: All nodes firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - { port: 'ssh', protocol: 'tcp' }
    - { port: '6783', protocol: 'tcp' }
    - { port: '6783', protocol: 'udp' }
    - { port: '6784', protocol: 'udp' }
    - { port: '10250', protocol: 'tcp' }

- name: Masters firewall [proto]
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - { port: '6443', protocol: 'tcp' }
    - { port: '2379', protocol: 'tcp' }
    - { port: '2380', protocol: 'tcp' }
    - { port: '10251', protocol: 'tcp' }
    - { port: '10252', protocol: 'tcp' }
    - { port: '10255', protocol: 'tcp' }
  when: inventory_hostname in groups['masters']

- name: Nodes firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - { port: '30000:32767', protocol: 'tcp' }
  when: inventory_hostname not in groups['masters']

- name: Enable UFW
  community.general.ufw:
    state: enabled
  async: 10
  poll: 5
    
- name: Enable & start firewall [ufw]  
  ansible.builtin.systemd:
    name: ufw
    enabled: yes
    state: restarted