---
- name: Download firewall
  ansible.builtin.apt:
    pkg: ufw
    state: present

- name: Deny policy
  community.general.ufw:
    policy: deny

- name: All nodes firewall
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
    src: "{{ INTERNAL_NETWORK }}/{{ MASK }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
  async: 10
  poll: 5
    
- name: Enable & start firewall [ufw]  
  ansible.builtin.systemd:
    name: ufw
    enabled: yes
    state: restarted