apiVersion: v1
kind: PersistentVolume
metadata:
    name: shared-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/home/imane/Desktop/test/learn/data"