apiVersion: apps/v1  
kind: Deployment       
metadata:       
  name: manapy-deploy
spec:           
  replicas: 1
  selector:
    matchLabels:
      app: manapy-deploy
  template:
    metadata:       
      name: manapy-deploy
      labels:
        app: manapy-deploy
    spec:   
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - worker
      containers:
        - name: manapy
          image: faiithbyte/manapy
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shared-storage