apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: master
    path: /mnt/shared/