apiVersion: apps/v1 
kind: Deployment      
metadata:      
  name: paraviewweb-deploy
  labels:
    app: paraviewweb
spec:          
  replicas: 1
  selector:
    matchLabels:
      app: paraviewweb
  template:
    metadata:       
      name: paraviewweb
      labels:
        app: paraviewweb
    spec:     
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - visualizer  
      containers:
        - name: paraviewweb
          image: faiithbyte/visualizer
          ports:
            - containerPort: 80
          env:
            - name: PROTOCOL
              value: "ws"
            - name: SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shared-storage