---
- name: NFS firewall
  community.general.ufw:
    rule: allow
    port: nfs
    src: "{{ INTERNAL_NETWORK }}/{{ MASK }}"
  ignore_errors: yes

- name: Firewall reload
  community.general.ufw:
    state: reloaded
  ignore_errors: yes

- name: Install dependencies
  ansible.builtin.apt:
    pkg: nfs-kernel-server
    state: present

- name: Create shared folder
  ansible.builtin.file:
    path: "{{ shared_folder }}"
    state: directory
    owner: nobody
    group: nogroup

- name: Add network to nfs file
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ shared_folder }} {{ INTERNAL_NETWORK }}/{{ MASK }}(rw,sync,no_subtree_check)"
    state: present
    create: yes

- name: export
  ansible.builtin.shell:
    cmd: exportfs -a

- name: Enable & start nfs server  
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: yes
    state: restarted