---

- name: NFS Firewall Setup
  ansible.posix.firewalld:
    # zone: internal
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - nfs #2049
    - rpc-bind #111
    - mountd
  when: 
    - ansible_facts.services is defined
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == 'running'