---
- name: Add master IP to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars['master'].ansible_host }} {{ hostvars['master'].inventory_hostname }}"
    create: yes
    state: present

- name: Install dependencies
  ansible.builtin.apt:
    pkg: nfs-common
    state: present

- name: Create shared folder
  ansible.builtin.file:
    path: /mnt/shared
    state: directory

- name: Mount shared folders
  ansible.builtin.shell:
    cmd: "mount {{ hostvars['master'].inventory_hostname }}:{{ item }} {{ item }}"
  with_items:
    - /mnt/shared
    - /home 