- name: Download Kubernetes
  hosts: all
  tasks:
  - name: Update
    ansible.builtin.apt:
      update_cache: yes
  roles:
    - firewall

- name: Setup DNS Server
  hosts: dns_servers
  roles:
    - dns-server

- name: Setup DNS Clients
  hosts: all
  roles:
    - dns-client

- name: Download Kubernetes
  hosts: cluster
  roles:
    - docker
    - kubernetes

# ============= DEV =======================
- name: Download kubebuilder
  hosts: master
  roles:
    - kubebuilder
    - manapy
# =========================================

- name: Setup Cluster
  hosts: masters
  roles:
    - nfs-server
    - cluster

- name: Join nodes
  hosts: cluster
  roles:
    - add-node

- name: Setup NFS client
  hosts: nodes
  roles:
    - nfs-client
