- name: Download Kubernetes
  hosts: all
  tasks:
  - name: Update
    ansible.builtin.apt:
      update_cache: yes
  roles:
    - firewall

- name: Setup DNS Server
  hosts: dns_servers
  roles:
    - dns-server

- name: Setup NFS Server
  hosts: nfs_servers
  roles:
    - nfs-server

- name: Setup DNS Clients
  hosts: all
  roles:
    - dns-client

- name: 
  hosts: cluster
  roles:
    - docker
    - kubernetes
    - nfs-client

- name: Setup Cluster
  hosts: masters
  roles:
    - cluster

- name: Join nodes
  hosts: cluster
  roles:
    - add-node
