- name: Download Kubernetes
  hosts: all
  tasks:
  - name: Update
    ansible.builtin.apt:
      update_cache: yes

- name: Download Kubernetes
  hosts: all
  roles:
    - etc-hosts # remove this after dns setup
    - firewall
    - docker
    - kubernetes

- name: Setup Cluster
  hosts: masters
  roles:
    - nfs-server
    - cluster
    - manapy

- name: Join nodes
  hosts: all
  roles:
    - add-node
  
- name: NFS client
  hosts: nodes
  roles:
    - nfs-client
