- name: Download Kubernetes
  hosts: all
  roles:
    - setup
    - docker
    - kubernetes

- name: Setup Cluster
  hosts: master
  roles:
    - nfs-server
    - cluster
    - manapy

- name: Join nodes
  hosts: nodes
  roles:
    - nodes
    - nfs-client

- name: Label nodes 
  hosts: master
  roles:
    - labels
