- name: Download Kubernetes
  hosts: all
  roles:
    - docker
    - kubernetes

- name: Setup Cluster
  hosts: master
  roles:
    - cluster
    - manapy

- name: Join nodes
  hosts: visualizers, workers
  roles:
    - nodes

- name: Label nodes 
  hosts: master
  roles:
    - labels