---
- name: Delete
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ inventory_hostname }}'
    state: absent

- name: Add IP to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    create: yes
    state: present

- name: Add master IP to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars['master'].ansible_host }} {{ hostvars['master'].inventory_hostname }}"
    create: yes
    state: present

- name: Join cluster
  ansible.builtin.shell:
    "{{ hostvars['master'].join_cluster }}"

