masters:
  hosts:
    master:

workers:
  hosts:
    node1:

visualizers:
  hosts:
    node2:

# -------------------------------
nodes:
  children:
    workers:
    visualizers:

all:
  children:
    masters:
    workers:
    visualizers: