# all:
masters:
  hosts:
    master:
      ansible_host: 192.168.56.1
workers:
  hosts:
    node-01:
      ansible_host: 192.168.56.11
visualizers:
  hosts:
    node-02:
      ansible_host: 192.168.56.12