masters:
  hosts:
    master:

workers:
  hosts:
    node1:
    node2:

visualizers:
  hosts:

dns_servers:
  hosts:
    dns:

nfs_servers:
  hosts:
    nfs:
# -------------------------------
nodes:
  children:
    workers:
    visualizers:

cluster:
  children:
    masters:
    workers:
    visualizers:

all:
  children:
    masters:
    workers:
    visualizers:
    dns_servers:
    nfs_servers:
  vars:
    DOMAIN: cluster.kaas
    # network
    MASK: 24
    LONG_MASK: 255.255.255.0
    INTERNAL_NETWORK: 192.168.56.0
