masters:
  hosts:
    master:

workers:
  hosts:
    node1:
    node2:

visualizers:
  hosts:

dns_servers:
  hosts:
    dns:

# -------------------------------
nodes:
  children:
    workers:
    visualizers:

all:
  children:
    masters:
    workers:
    visualizers: