masters:
  hosts:
    master:

workers:
  hosts:
    node1:
    node2:

visualizers:
  hosts:

dns_servers:
  hosts:
    dns:

# -------------------------------
nodes:
  children:
    workers:
    visualizers:

cluster:
  children:
    masters:
    workers:
    visualizers:

all:
  children:
    masters:
    workers:
    visualizers:
    dns_servers:
  vars:
    DOMAIN: cluster.kaas
    INTERNAL_NETWORK: 192.168.56.0
    SHORT_MASK: 24