---
- name: Setup shared volume
  ansible.builtin.shell: |
    kubectl apply -f {{ playbook_dir }}/roles/manapy/files/nfs-volume.yaml
    kubectl apply -f {{ playbook_dir }}/roles/manapy/files/nfs-claim-rw.yaml
# kubectl apply -f {{ playbook_dir }}/roles/manapy/files/nfs-claim-ro.yaml

- name: Setup paraviewweb visualizer
  ansible.builtin.shell: |
    kubectl apply -f {{ playbook_dir }}/roles/manapy/files/paraview.yaml
    kubectl apply -f {{ playbook_dir }}/roles/manapy/files/service.yaml

- name: Setup manapy
  ansible.builtin.shell:
    kubectl apply -f {{ playbook_dir }}/roles/manapy/files/manapy.yaml