---  
- name: Update
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependancies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
    state: present

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: '0444'
    force: true

- name: System architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: architecture

- name: System codename
  ansible.builtin.shell: "grep '^VERSION_CODENAME=' /etc/os-release | cut -d = -f2"
  register: codename

- name: Add Docker to apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codename.stdout }} stable"
    filename: /etc/apt/sources.list.d/docker.list
    state: present
    update_cache: true

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
    state: present

- name: Enable & start docker  
  ansible.builtin.systemd:
    name: "docker"
    enabled: yes
    state: restarted