---
- name: Update
  ansible.builtin.apt:
    update_cache: yes

- name: Delete
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ inventory_hostname }}'
    state: absent

- name: Add master IP to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
    create: yes
  loop: "{{ groups['all'] }}"

# - name: Download firewall
#   ansible.builtin.apt:
#     pkg: ufw
#     state: present

# - name: Configure to accept ssh
#   community.general.ufw:
#     rule: allow
#     port: ssh
#     proto: tcp

# - name: Reload UFW
#   community.general.ufw:
#     state: reloaded

# - name: Reject policy and enable UFW
#   community.general.ufw:
#     state: enabled
#     policy: deny

# - name: Configure to accept ssh
#   community.general.ufw:
#     rule: allow
#     port: ssh
#     proto: tcp

# - name: Enable & start firewall [ufw]  
#   ansible.builtin.systemd:
#     name: ufw
#     state: restarted