---
# - name: Configure firewall
#   community.general.ufw:
#     rule: allow
#     port: "{{ item }}"
#     proto: tcp
#   with_items:
#     - 6443
#     - 2379
#     - 2380
#     - 10250
#     - 10251
#     - 10252
#     - 10255

# - name: Reload UFW
#   community.general.ufw:
#     state: reloaded
      
- name: Init cluster
  ansible.builtin.shell:
    cmd: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }}

- name: "..."
  ansible.builtin.shell: | 
    mkdir -p $HOME/.kube
    cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
    
- name: Install network addon
  ansible.builtin.shell:
    cmd: kubectl apply -f https://reweave.azurewebsites.net/k8s/v1.29/net.yaml

- name: Get join command
  ansible.builtin.shell: 
    cmd: kubeadm token create --print-join-command
  register: join

- name: Set join command
  ansible.builtin.set_fact:
    join_cluster: "{{ join.stdout_lines[0] }}"