---
- name: Node firewall [kube]
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - { port: '6783', protocol: 'tcp' }
    - { port: '6783', protocol: 'udp' }
    - { port: '6784', protocol: 'udp' }
    - { port: '10250', protocol: 'tcp' }
    # - { port: '30000:32767', protocol: 'tcp' }
  ignore_errors: yes

- name: Get command to join the cluster
  ansible.builtin.shell: 
    cmd: kubeadm token create --print-join-command
  register: join
  delegate_to: "{{ groups['masters'] | first }}"
  run_once: yes
  when: inventory_hostname in groups['masters']

- name: Set command to join the cluster
  ansible.builtin.set_fact:
    join_cluster: "{{ join.stdout }}"
  delegate_to: "{{ groups['masters'] | first }}"
  run_once: yes
  when: inventory_hostname in groups['masters']

- name: Join cluster
  ansible.builtin.shell:
    "{{ hostvars[groups['masters'] | first].join_cluster }}"
  when: inventory_hostname not in groups['masters']

- name: Label visualizers nodes
  ansible.builtin.shell:
    cmd: kubectl label node {{ item }} type=visualizer
  loop: "{{ groups['visualizers'] }}"
  run_once: true
  when: inventory_hostname in groups['masters']

- name: Label workers nodes
  ansible.builtin.shell:
    cmd: kubectl label node {{ item }} type=worker
  loop: "{{ groups['workers'] }}"
  run_once: true
  when: inventory_hostname in groups['masters']
