---

- name: DNS Firewall Setup
  ansible.posix.firewalld:
    # zone: internal
    service: dns #53
    permanent: true
    state: enabled
    immediate: true
  when: 
    - ansible_facts.services is defined
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == 'running'