---
- name: Install dependencies
  ansible.builtin.apt:
    pkg: nfs-common
    state: present

- name: Create shared folder
  ansible.builtin.file:
    path: /data
    state: directory

- name: Specify allowed clients
  ansible.builtin.template:
    src: data.mount.j2
    dest: /etc/systemd/system/data.mount

- name: Enable & start autofs
  ansible.builtin.systemd:
    name: data.mount
    enabled: yes
    state: started