---
- name: Unmount swap
  ansible.builtin.shell:
    cmd: swapoff -a
    
- name: Disable swap
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '\sswap\s+sw\s+'
    state: absent

- name: Create a file for the containerd module
  ansible.builtin.file:
    path: /etc/modules-load.d/containerd.conf
    state: touch

- name: Configure modules for containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Load modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: 
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: Install containerd
  ansible.builtin.apt:
    pkg:
      - containerd.io
    state: present

- name: Change containerd config
  ansible.builtin.shell:
    cmd: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1 

- name: Configuring Systemd cgroup driver for containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "            SystemdCgroup = false"
    line: "            SystemdCgroup = true"

- name: Enable & start containerd  
  ansible.builtin.systemd:
    name: "containerd"
    enabled: yes
    state: restarted 

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  retries: 5
  delay: 3
  register: job
  until: job.failed == false

- name: Add Kubernetes repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    filename: /etc/apt/sources.list.d/kubernetes.list
    state: present
    update_cache: true

- name: Install kubeadm...
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl

