---
# - name: Copy manapy dockerfile
#   ansible.builtin.copy:
#     src: ../files/Dockerfile
#     dest: .
#     force: yes

# - name: Build manapy image
#   community.docker.docker_image:
#     build: 
#       path: .
#     source: build
#     name: "{{ DOCKER_IMAGE_NAME }}"
#   register: output

# - name: Start manapy container
#   community.docker.docker_container:
#     name: "{{ DOCKER_CONTAINER_NAME }}"
#     image: "{{ DOCKER_IMAGE_NAME }}"

- name: Install dependancies
  ansible.builtin.apt:
    pkg:
      - ca-certificates 
      - apt-transport-https 
      - gpg
    state: present

- name: keyrings
  ansible.builtin.command:
    cmd: install -m 0755 -d /etc/apt/keyrings

# - name: Download the docker GPG file
#   ansible.builtin.get_url:
#     url: "https://download.docker.com/linux/debian/gpg"
#     dest: "/etc/apt/keyrings/docker.asc"
    
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list

- name: Update
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
  state: present

- name: Update
  ansible.builtin.apt:
    update_cache: yes

- name: Install kube
  ansible.builtin.apt:
    pkg:
      - kubelet 
      - kubeadm 
      - kubectl
    state: present

sudo apt-mark hold kubelet kubeadm kubectl

- name: Enable & start kubelet
  ansible.builtin.systemd:
    name: "kubelet"
    enabled: yes
    state: restarted

- name: Get Minikube binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "minikube"

- name: Change minikube executable permissions
  file:
    path: "minikube"
    mode: "0777"

- name: Install Minikube
  ansible.builtin.shell:
    mkdir -p /usr/local/bin/
    install minikube /usr/local/bin/
    minikube start

